---
- name: Install Desktop for Ubuntu
  become: yes
  apt:
    name: ubuntu-desktop
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Desktop for Debian
  become: yes
  apt:
    name: task-gnome-desktop
    state: latest
  when: ansible_distribution == "Debian"
  
- name: Install Desktop for CentOS
  become: yes
  yum:
    name:
      - "@development-tools"
      - "@^gnome-desktop-environment"
      - "@x11"
    state: latest
  when: ansible_distribution == "CentOS"

- name: Set Gnome as Default
  become: yes
  shell:
    cmd: systemctl set-default graphical.target