---
- name: ensure httpd is at the latest version
  become: yes
  yum:
    name: httpd
    state: latest
  when: ansible_distribution == "CentOS"

- name: start httpd on boot
  become: yes
  systemd:
    name: httpd
    enabled: yes
    state: restarted
  when: ansible_distribution == "CentOS"

- name: ensure apache is at the latest version
  become: yes
  apt:
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  
- name: start apache on boot
  become: yes
  systemd:
    name: apache2
    enabled: yes
    state: restarted
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"